[highlight]
noClasses = false

[tableOfContents]
startLevel = 2
endLevel = 4
ordered = false

[goldmark]

[goldmark.renderer]
unsafe = true
xhtml = true

[goldmark.parser.attribute]
block = true
title = true