#### Main Navigation ###########

[[global]]
name = "Get Started"
identifier = "get-started"
url = "/get-started"
weight = 10

[[global]]
name = "Components"
identifier = "components"
url = "/components"
weight = 45

[[global]]
name = "Docs"
identifier = "docs"
url = "/docs"
weight = 25

[[global]]
name = "Tokens"
identifier = "tokens"
url ="/tokens"
weight=15