#### Main Navigation ###########

[[global]]
name = "Components"
identifier = "components"
url = "/components"
weight = 45

[[global]]
name = "Docs"
identifier = "docs"
url = "/docs"
weight = 25

[[global]]
name = "Tokens"
identifier = "tokens"
url ="/tokens"
weight=15