[[mounts]]
source = "site/content"
target = "content"

[[mounts]]
source = "site/assets"
target = "assets"

[[mounts]]
source = "site/layouts"
target = "layouts"

[[mounts]]
source = "site/static"
target = "static"

[[mounts]]
source = "site/data"
target = "data"

[[mounts]]
source = "dist"
target = "static"
