baseURL = "https://fastbootstrap.com"
languageCode = "en"
title = "Awesome Bootstrap Theme with Atlassian Design - FastBootstrap"

enableRobotsTXT = true
disableKinds = ["404", "taxonomy", "term", "RSS"]

publishDir = "_site"
enableInlineShortcodes = true

[outputs]
home = ["HTML", "JSON", "RSS"]

[params]
description = "FastBootstrap is a beautiful Bootstrap theme for your next project with quick start. Powerful and free UI Kits that designed with Atlassian Design."
page_title_suffix = "FastBootstrap Theme"
github_org = "https://github.com/fastbootstrap"
repo = "https://github.com/fastbootstrap/atlassian-design-for-bootstrap"
current_version = "2.0.0"
download.source = "https://github.com/fastbootstrap/atlassian-design-for-bootstrap/archive/refs/tags/v2.0.0.zip"

[params.cdn]
css = "https://cdn.jsdelivr.net/npm/fastbootstrap@2.0.0/dist/css/fastbootstrap.min.css"
css_hash = "sha256-EkS1lBVeD1Dv7HGBICgtEPKeIz4ffoKbo5gRiPvD6/8="
js = "https://cdn.jsdelivr.net/npm/fastbootstrap@2.0.0/dist/js/fastbootstrap.min.js"
js_hash = "sha256-o0tNXN7ia0O9G0qNbrzBkEEiQTv+GeW5EO4LjnfDkZk="
