baseURL = "https://fastbootstrap.com"
languageCode = "en"
title = "FastBootstrap: Bootstrap UI Components with Atlassian Design"

enableRobotsTXT = true
disableKinds = ["404", "taxonomy", "term", "RSS"]

publishDir = "_site"
enableInlineShortcodes = true

[outputs]
home = ["HTML", "JSON", "RSS"]

[params]
description = "Atlassian Design for Bootstrap 5. Powerful and free UI Kits for Bootstrap with Atlassian Design."
page_title_suffix = "FastBootstrap"
github_org = "https://github.com/fastbootstrap"
repo = "https://github.com/fastbootstrap/atlassian-design-for-bootstrap"
version_tag = "v1.1.1"

[params.cdn]
css = "https://cdn.jsdelivr.net/npm/fastbootstrap@1.1.1/dist/css/fastbootstrap.min.css"
css_hash = "sha256-Yzz+k0rjOAAPX4Nkr73zQvppd6buXomR9n4uQ5lrSYE="
js = "https://cdn.jsdelivr.net/npm/fastbootstrap@1.1.1/dist/js/fastbootstrap.min.js"
js_hash = "sha256-EA7CcsZVlKgu1Vdk1Nsl648ddvyavbdyjR/vnaTuomk="
