baseURL = "https://fastbootstrap.com"
languageCode = "en"
title = "FastBootstrap: Bootstrap UI Components with Atlassian Design"

enableRobotsTXT = true
disableKinds = ["404", "taxonomy", "term", "RSS"]

publishDir = "_site"
enableInlineShortcodes = true

[outputs]
home = ["HTML", "JSON", "RSS"]

[params]
description = "Atlassian Design for Bootstrap 5. Powerful and free UI Kits for Bootstrap with Atlassian Design."
page_title_suffix = "FastBootstrap"
github_org = "https://github.com/fastbootstrap"
repo = "https://github.com/fastbootstrap/atlassian-design-for-bootstrap"
download_url = "https://github.com/fastbootstrap/atlassian-design-for-bootstrap/archive/refs/tags/v1.0.0.zip"

[params.cdn]
css = "https://cdn.jsdelivr.net/npm/fastbootstrap@1.0.0/dist/css/fastbootstrap.min.css"
css_hash = "sha256-l/Z23rB0iuouhJeosXkeGLQ0nb/vAambyGHvRdkvhgY="
js = "https://cdn.jsdelivr.net/npm/fastbootstrap@1.0.0/dist/js/fastbootstrap.min.js"
js_hash = "sha256-zbV7fX6B18iSazTO6D/2M41vSfdOFeOwVE6mRLd49tg="
