baseURL = "https://fastbootstrap.com"
languageCode = "en"
title = "Awesome Bootstrap Theme with Atlassian Design - FastBootstrap"

enableRobotsTXT = true
disableKinds = ["404", "taxonomy", "term", "RSS"]

publishDir = "_site"
enableInlineShortcodes = true

[outputs]
home = ["HTML", "JSON", "RSS"]

[params]
description = "FastBootstrap is a beautiful Bootstrap theme for your next project with quick start. Powerful and free UI Kits that designed with Atlassian Design."
page_title_suffix = "FastBootstrap Theme"
github_org = "https://github.com/fastbootstrap"
repo = "https://github.com/fastbootstrap/atlassian-design-for-bootstrap"
current_version = "1.1.2"
download.source = "https://github.com/fastbootstrap/atlassian-design-for-bootstrap/archive/refs/tags/v1.1.2.zip"

[params.cdn]
css = "https://cdn.jsdelivr.net/npm/fastbootstrap@1.1.2/dist/css/fastbootstrap.min.css"
css_hash = "sha256-xLGBU65wCDv2/qEdq3ZYw2Qdiia/wxxeGepRyZmpQdY="
js = "https://cdn.jsdelivr.net/npm/fastbootstrap@1.1.2/dist/js/fastbootstrap.min.js"
js_hash = "sha256-+c+/OCMmtlZadi89VaV1yUOkk1T4BD2pwBFpY3OcrqI="
